### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by noguchi-yu** [noguchi-yu/kyushu_travel#42]
### 概要
[GitHubProject](https://github.com/users/noguchi-yu/projects/1)

### 実装予定の機能（MVPリリース）
- [ ] 会員登録・ログイン(Devise)
- [ ] マイページ
- [ ] 新規スポット投稿（Google Places APIを使用した住所・スポット名のオートコンプリート）
- [ ] スポット編集
- [ ] スポット削除
- [ ] タグ機能
- [ ] 検索（フリーワード、地域、タグ）
- [ ] 投稿一覧（GoogleマップAPIを使用しマップ上にアイコンで表示）
- [ ] 投稿詳細

### 必要なページ
- [ ] Topページ
- [ ] ログインページ
- [ ] ログイン後のTopページ
- [ ] 新規会員登録ページ
- [ ] パスワード再設定ページ（email送信フォーム）
- [ ] パスワード再設定ページ（新しいパスワード設定フォーム）
- [ ] お問い合わせ入力、内容確認、完了ページ
- [ ] プライバシーポリシーページ
- [ ] 利用規約ページ
- [ ] マイページ
- [ ] プロフィール設定
- [ ] 自分の投稿一覧ページ
- [ ] 新規投稿ページ
- [ ] 新規編集ページ
- [ ] 投稿一覧ページ
- [ ] 投稿詳細ページ（簡易モーダル表示）
- [ ] 投稿詳細ページ

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくて良いかもと思ったものになります。
- i18n
- マイページ
- favicon
- ドメイン
- プライバシーポリシー
- 利用規約
- お問い合わせ

**Comment by noguchi-yu** [comment]
@Tsuchiya2 講師
ご確認いただきありがとうございます。
MVPに含めなくて良いものについて本リリース時に対応したいと思います。ご教示いただきありがとうございます。
マイページについてはREADMEのMVPリリース項目にも記載しておりましたので、その後の機能項目へ記載修正したいと思います。
