### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by noguchi-yu** [noguchi-yu/kyushu_travel#80]
ご確認よろしくお願いいたします。
## 各種情報
サービス名：Kyushu Travel
サービスURL：https://kyushu-travel.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録・ログイン(Devise)
- [x] 新規スポット投稿（Google Places APIを使用した住所・スポット名のオートコンプリート）
- [x] スポット編集
- [x] スポット削除
- [x] タグ機能
- [x] 投稿一覧（GoogleマップAPIを使用しマップ上にアイコンで表示）
- [x] 投稿詳細
- [ ] マイページ
- [ ] 検索（フリーワード、地域、タグ）

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
なければこの項目は省略してください
- 下記項目について本リリースまでに実装（卒業認定までの開発スケジュール見積もり面談にてご相談済み）
- [ ] マイページ
- [ ] 検索（フリーワード、地域、タグ）
- [ ] 日本語化対応
- [ ] レスポンジブ対応

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします
- 会員登録・ログイン
[![Image from Gyazo](https://i.gyazo.com/c32734c41da97a99bab1ba0de2667f39.gif)](https://gyazo.com/c32734c41da97a99bab1ba0de2667f39)
- 新規スポット投稿（Google Places APIを使用した住所・スポット名のオートコンプリート）
  [![Image from Gyazo](https://i.gyazo.com/39b9c709ecdbd766464e53427321bdec.gif)](https://gyazo.com/39b9c709ecdbd766464e53427321bdec)
- スポット編集
  [![Image from Gyazo](https://i.gyazo.com/815060801ed8ce0858a87a7b65c55748.gif)](https://gyazo.com/815060801ed8ce0858a87a7b65c55748)
- スポット削除
  [![Image from Gyazo](https://i.gyazo.com/736bdfd8a4dcc4a4e6e45acc070047a4.gif)](https://gyazo.com/736bdfd8a4dcc4a4e6e45acc070047a4)
- 投稿一覧（GoogleマップAPIを使用しマップ上にアイコンで表示）
  [![Image from Gyazo](https://i.gyazo.com/11b1a403dd4bc0b38195485f4a74c9ea.jpg)](https://gyazo.com/11b1a403dd4bc0b38195485f4a74c9ea)
- 投稿簡易詳細（モーダル）
  [![Image from Gyazo](https://i.gyazo.com/d76ead62f53f506ff3cf6b081d8667aa.jpg)](https://gyazo.com/d76ead62f53f506ff3cf6b081d8667aa)
- 投稿詳細
  [![Image from Gyazo](https://i.gyazo.com/3120729bd672e755ec8a8f204ccf2b07.gif)](https://gyazo.com/3120729bd672e755ec8a8f204ccf2b07)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
